name: prayer
description: "The Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: 8.0.3
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

   
  realm: ^2.0.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  auto_route_generator: 8.0.0
  retrofit_generator: 8.1.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
